src/doclist/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tasks.urls")),
]

src/tasks/urls.py
from django.urls import path
from tasks import views

app_name = "tasks"

urlpatterns = [
    path("", views.index, name="home"),
    path("add-collection/", views.add_collection, name="add-collection"),
    path("add-task/", views.add_task, name="add-task"),
    path("delete-task/<int:task_pk>", views.delete_task, name="delete-task"),
    path(
        "delete-collection/<int:collection_pk>", views.delete_collection, name="delete-collection"
    ),
    path("get-tasks/<int:collection_pk>", views.get_tasks, name="get-tasks"),
]

src/tasks/models.py
from django.db import models


class Collection(models.Model):
    name = models.CharField(max_length=60)
    slug = models.SlugField()

    @classmethod
    def get_default_collection(cls):
        collection, _ = cls.objects.get_or_create(name="Défaut", slug="_defaut")
        return collection

    def __str__(self):
        return self.name


class Task(models.Model):
    description = models.CharField(max_length=300)
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE)

    def __str__(self):
        return f"Task ({self.collection.name}): {self.description}"

src/tasks/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.html import escape
from django.utils.text import slugify
from tasks.models import Collection
from tasks.models import Task


def index(request):
    context = dict()

    collection_slug = request.GET.get("collection")

    if not collection_slug:
        Collection.get_default_collection()
        return redirect(f"{reverse('tasks:home')}?collection=_defaut")

    collection = get_object_or_404(Collection, slug=collection_slug)

    context["collections"] = Collection.objects.order_by("slug")
    context["collection"] = collection
    context["tasks"] = collection.task_set.order_by("description")

    return render(request, "tasks/index.html", context=context)


def add_collection(request):
    # si l'utilisateur saisit des caractères spéciaux ou du code JavaScript
    # dans le champ "collection-name," ces caractères spéciaux seront échappés,
    # ce qui permettra de ne pas interpréter le code.
    collection_name = escape(request.POST.get("collection-name"))
    collection, created = Collection.objects.get_or_create(
        name=collection_name, slug=slugify(collection_name)
    )
    if not created:
        return HttpResponse("La collection existe déjà.", status=409)

    return render(request, "tasks/collection.html", context={"collection": collection})


def delete_collection(request, collection_pk):
    Collection.objects.get(pk=collection_pk).delete()
    return redirect("tasks:home")


def add_task(request):

    # request.POST contient 'collection' grâce à hx-vals
    try:
        collection = Collection.objects.get(slug=request.POST.get("collection"))
    except Collection.DoesNotExist:
        collection = Collection.get_default_collection()

    description = escape(request.POST.get("task-description"))
    task = Task.objects.create(description=description, collection=collection)

    return render(request, "tasks/task.html", context={"task": task})


def delete_task(request, task_pk):
    Task.objects.get(pk=task_pk).delete()
    return HttpResponse("")


def get_tasks(request, collection_pk):
    collection = get_object_or_404(Collection, pk=collection_pk)
    tasks = collection.task_set.order_by("description")

    return render(request, "tasks/tasks.html", context={"tasks": tasks, "collection": collection})

src/tasks/templates/tasks/collection.html
<button class="list-group-item list-group-item-action {% if request.GET.collection == collection.slug %}active{% endif %}"
        data-bs-toggle="list"
        hx-get="{% url 'tasks:get-tasks' collection.pk %}"
        hx-push-url="?collection={{collection.slug}}"
        hx-target="#tasks-container">
    {{ collection.name }}
</button>

src/tasks/templates/tasks/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>DocList</title>

    <script src="https://unpkg.com/htmx.org@1.9.6"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>

<div class="container mx-auto mt-5">
    <h1>DocList</h1>

    <div class="row">
        <div class="col-4">
            <nav id="collections" class="list-group" role="tablist">
                {% for collection in collections %}
                    {% include 'tasks/collection.html' with collection=collection %}
                {% endfor %}
            </nav>

            <form class="d-flex gap-2 mt-2" method="POST" action="{% url 'tasks:add-collection' %}">
                {% csrf_token %}

                <input class="form-control" type="text" name="collection-name" placeholder="Collection...">
                <button class="btn btn-success"
                        hx-post="{% url 'tasks:add-collection' %}"
                        hx-target="#collections"
                        hx-swap="beforeend"
                        type="submit"
                >Ajouter</button>
            </form>
        </div>

        <section class="col-8">
            <form class="d-flex gap-2" method="POST">
            {% csrf_token %}

            <input class="form-control" type="text" name="task-description" placeholder="Tâche...">
            <button class="btn btn-success"
                    hx-post="{% url 'tasks:add-task' %}"
                    hx-target="#tasks-html"
                    hx-vals="js:{collection: getCollectionFromURL()}"
                    hx-swap="beforeend"
                    type="submit">
                Ajouter
            </button>
            </form>

            <section id="tasks-container">
                {% include 'tasks/tasks.html' with tasks=tasks collection=collection %}
            </section>
        </section>

    </div>
</div>

<script>
    document.body.addEventListener("htmx:responseError", function(evt) {
        alert(evt.detail.xhr.responseText);
    })

    function getCollectionFromURL() {
        let url = new URL(window.location.href);
        let searchParams = url.searchParams;
        return searchParams.get("collection");
    }
</script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

src/tasks/templates/tasks/task.html
<form method="POST" class="d-flex justify-content-between">
    {% csrf_token %}
    <p class="mb-0">{{ task.description }}</p>
    <button class="btn btn-danger"
            hx-post="{% url 'tasks:delete-task' task.pk%}"
            hx-target="closest form"
            hx-swap="outerHTML"
            hx-confirm="Voulez-vous vraiment supprimer cette tâche?"
            type="submit">Supprimer
    </button>
</form>

src/tasks/templates/tasks/tasks.html
<div id="tasks-html" class="d-flex flex-column gap-2 mt-2">
    {% for task in tasks %}
        {% include 'tasks/task.html' with task=task %}
    {% endfor %}
</div>

{% if collection.slug != "_defaut" %}
    <a href="{% url 'tasks:delete-collection' collection.pk %}">Supprimer la collection</a>
{% endif %}